name: fit_body
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^2.0.1
  firebase_core: ^4.7.0
  image_picker: ^1.0.7
  fl_chart: ^0.68.0
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

# ----------------------------------------------------
# 1. Launcher Icon Configuration
# ----------------------------------------------------
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/ic_logo.png"
  adaptive_icon_background: "#1A1025"
  adaptive_icon_foreground: "assets/icons/ic_logo.png"

# ----------------------------------------------------
# 2. Native Splash Screen Configuration
# ----------------------------------------------------
flutter_native_splash:
  color: "#1A1025"
  image: "assets/icons/ic_logo.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/icons/