// lib/constants/app_assets.dart
class AppAssets {
  AppAssets._();
  // ── Background Images ──────────────────────────────────────────────────────
  static const splashBg          = 'assets/images/splash_bg.png';
  static const onboard1Bg        = 'assets/images/onboard1_bg.png';
  static const onboard2Bg        = 'assets/images/onboard2_bg.png';
  static const onboard3Bg        = 'assets/images/onboard3_bg.png';
  static const homeLogo          = 'assets/images/home_logo.png';
  static const profilePhoto      = 'assets/images/profile_photo.png';
  // ── Setup Images ───────────────────────────────────────────────────────────
  static const setupBg           = 'assets/images/setup_bg.jpg';
  // ── Workout Images ─────────────────────────────────────────────────────────
  static const workoutThumb1     = 'assets/images/workout_thumb1.png';
  static const workoutThumb2     = 'assets/images/workout_thumb2.png';
  static const workoutGlutes     = 'assets/images/workout_glutes.png';
  static const workoutCardio     = 'assets/images/workout_cardio.png';
  static const workoutResistance = 'assets/images/workout_resistance.png';
  static const workoutAdvBanner  = 'assets/images/workout_advanced_banner.png';
  static const workoutCardioBoxing = 'assets/images/workout_cardio_boxing.png';
  static const workoutHypertrophy = 'assets/images/workout_hypertrophy.png';
  static const workoutRest       = 'assets/images/workout_rest.png';
  static const workoutSquats     = 'assets/images/workout_squats.png';
  static const workoutDumbbellMan = 'assets/images/workout_dumbbell_man.png';
  static const workoutAdvVideo   = 'assets/images/workout_advanced_video.png';
  // ── Exercise Images ────────────────────────────────────────────────────────
  static const exBarbellRows     = 'assets/images/ex_barbell_rows.png';
  static const exHammerCurls     = 'assets/images/ex_hammer_curls.png';
  static const exLegPress        = 'assets/images/ex_leg_press.png';
  static const exCableChest      = 'assets/images/ex_cable_chest.png';
  static const exTricepDips      = 'assets/images/ex_tricep_dips.png';
  static const exPushUps         = 'assets/images/ex_push_ups.png';
  // ── Favorites Images ───────────────────────────────────────────────────────
  static const favUpperBody      = 'assets/images/fav_upper_body.png';
  static const favPullOut        = 'assets/images/fav_pull_out.png';
  static const favLoopBand       = 'assets/images/fav_loop_band.png';
  static const favDumbbellStep   = 'assets/images/fav_dumbbell_step.png';
  static const favSplitStrength  = 'assets/images/fav_split_strength.png';
  static const favBoostEnergy    = 'assets/images/fav_boost_energy.png';
  static const favAvocadoToast   = 'assets/images/fav_avocado_toast.png';
  static const favLowerBody      = 'assets/images/fav_lower_body.png';
  static const favSmoothie       = 'assets/images/fav_smoothie.png';
  static const favHydrate        = 'assets/images/fav_hydrate.png';
  // ── Search Images ──────────────────────────────────────────────────────────
  static const searchSquat       = 'assets/images/search_squat.png';
  static const searchFullBody    = 'assets/images/search_full_body.png';
  static const searchCircuit     = 'assets/images/fav_pull_out.png';
  static const searchYogurt      = 'assets/images/search_yogurt.png';
  static const searchSplit       = 'assets/images/fav_split_strength.png';
  static const searchTurkey      = 'assets/images/search_turkey.png';
  // ── Nutrition Images ───────────────────────────────────────────────────────
  static const nutritionBanner   = 'assets/images/nutrition_banner.png';
  static const nutritionQuinoa   = 'assets/images/nutrition_quinoa.png';
  static const nutritionSalmon   = 'assets/images/nutrition_salmon.png';
  // ── Meal Plan Images ───────────────────────────────────────────────────────
  static const mealPlanBanner    = 'assets/images/meal_plan_banner.png';
  static const mealSpinach       = 'assets/images/meal_spinach_omelette.png';
  static const mealProteinShake  = 'assets/images/meal_protein_shake.png';
  static const mealGreenCelery   = 'assets/images/meal_green_celery.png';
  static const mealSalmonAvocado = 'assets/images/meal_salmon_avocado.png';
  static const mealQuinoaSalad   = 'assets/images/meal_quinoa_salad.png';
  static const mealBurrito       = 'assets/images/meal_burrito.png';
  static const mealTeriyaki      = 'assets/images/meal_teriyaki.png';
  static const mealIdeasBanner   = 'assets/images/meal_ideas_banner.png';
  static const mealGrilledChicken = 'assets/images/meal_grilled_chicken.png';
  static const mealChickpeaSalad = 'assets/images/meal_chickpea_salad.png';
  static const mealLentilSoup    = 'assets/images/meal_lentil_soup.png';
  static const mealChickenSpinach = 'assets/images/meal_chicken_spinach.png';
  // ── Weekly Challenge ───────────────────────────────────────────────────────
  static const weeklyChallenge   = 'assets/images/weekly_challenge.png';
  static const article1          = 'assets/images/article1.png';
  static const article2          = 'assets/images/article2.png';
  // ── Dashboard Thumbnails ───────────────────────────────────────────────────
  static const workoutThumbDash1 = 'assets/images/workout_thumb1.png';
  static const workoutThumbDash2 = 'assets/images/workout_thumb2.png';
  // ── Icons ──────────────────────────────────────────────────────────────────
  static const icActiveLIfestyle = 'assets/icons/ic_active_lifestyle.png';
  static const icNutrition       = 'assets/icons/ic_nutrition.png';
  static const icCommunity       = 'assets/icons/ic_community.png';
  static const icLogo            = 'assets/icons/ic_logo.png';
  static const icGoogle          = 'assets/icons/ic_google.png';
  static const icFacebook        = 'assets/icons/ic_facebook.png';
  static const icInstagram       = 'assets/icons/ic_instagram.png';
  static const icMale            = 'assets/icons/ic_male.png';
  static const icFemale          = 'assets/icons/ic_female.png';
  static const icWorkout         = 'assets/icons/ic_workout.png';
  static const icProgress        = 'assets/icons/ic_progress.png';
  static const icNavHome         = 'assets/icons/ic_nav_home.png';
  static const icNavWorkout      = 'assets/icons/ic_nav_workout.png';
  static const icNavFavorite     = 'assets/icons/ic_nav_favorite.png';
  static const icNavProfile      = 'assets/icons/ic_nav_profile.png';
}