// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmkYLPuO75YDHdI9h0pTWve-cLipGcu2k',
    appId: '1:968934522583:web:985af8d310dec83117fa92',
    messagingSenderId: '968934522583',
    projectId: 'fitbody-506ad',
    authDomain: 'fitbody-506ad.firebaseapp.com',
    storageBucket: 'fitbody-506ad.firebasestorage.app',
    measurementId: 'G-8HTMJ265JM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZzRoQMjQ8oef5-JXHjiZvWcKSwHnMsZc',
    appId: '1:968934522583:android:27754f942ce2828d17fa92',
    messagingSenderId: '968934522583',
    projectId: 'fitbody-506ad',
    storageBucket: 'fitbody-506ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4mwAlaaz5Fo3ZR-9_X05fl8YFDV6dHhM',
    appId: '1:968934522583:ios:1e0e6612b83b27e317fa92',
    messagingSenderId: '968934522583',
    projectId: 'fitbody-506ad',
    storageBucket: 'fitbody-506ad.firebasestorage.app',
    iosBundleId: 'com.example.fitBody',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4mwAlaaz5Fo3ZR-9_X05fl8YFDV6dHhM',
    appId: '1:968934522583:ios:1e0e6612b83b27e317fa92',
    messagingSenderId: '968934522583',
    projectId: 'fitbody-506ad',
    storageBucket: 'fitbody-506ad.firebasestorage.app',
    iosBundleId: 'com.example.fitBody',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmkYLPuO75YDHdI9h0pTWve-cLipGcu2k',
    appId: '1:968934522583:web:843e1547ccd7af1417fa92',
    messagingSenderId: '968934522583',
    projectId: 'fitbody-506ad',
    authDomain: 'fitbody-506ad.firebaseapp.com',
    storageBucket: 'fitbody-506ad.firebasestorage.app',
    measurementId: 'G-PWVNT54L7V',
  );
}
